In [1]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import re
import pandas as pd
import os
import requests
import csv

In [2]:
data = pd.read_csv('results.csv', sep=',',skiprows=14)

In [3]:
pd.set_option('display.max_rows', 500)

In [4]:
data

                                                                                                      112 €
SO/ Berlin Das Stue                                Mitte                            Der Preis beträgt 441 €
441 €                                              NaN                                                  NaN
The Kater                                          Berlin                           Der Preis beträgt 223 €
223 €                                              NaN                                                  NaN
Axel Hotel Berlin - Adults Only                    Berlin                           Der Preis beträgt 198 €
198 €                                              NaN                                                  NaN
Grimms Potsdamer Platz                             Mitte                            Der Preis beträgt 245 €
245 €                                              NaN                                                  NaN
Michels Apart Hotel Berlin                         Charlottenburg-Wilmersdorf  Der neue Preis beträgt 292 €
292 €                                              NaN                                                  NaN
MEININGER Hotel Berlin Airport                     Berlin                            Der Preis beträgt 84 €
84 €                                               NaN                                                  NaN
Hotel Müggelsee Berlin                             Berlin                       Der neue Preis beträgt 94 €
94 €                                               NaN                                                  NaN
Seminaris CampusHotel Lifestyle + Design Berlin    Berlin                      Der neue Preis beträgt 186 €
186 €                                              NaN                                                  NaN
Hotel Helle Mitte Berlin                           Berlin                       Der neue Preis beträgt 58 €
58 €                                               NaN                                                  NaN
DämeritzSeehotel                                   Hessenwinkel                     Der Preis beträgt 109 €
109 €                                              NaN                                                  NaN
MEININGER Hotel Berlin East Side Gallery           Berlin                           Der Preis beträgt 118 €
118 €                                              NaN                                                  NaN
Hotel Klassik Berlin                               Berlin                           Der Preis beträgt 108 €
108 €                                              NaN                                                  NaN
Honigmond Boutique Hotel Berlin-Mitte              Mitte                       Der neue Preis beträgt 189 €
189 €                                              NaN                                                  NaN
Exe Hotel Klee Berlin Excellence Class             Berlin                      Der neue Preis beträgt 195 €
195 €                                              NaN                                                  NaN
Vienna House Easy Berlin                           Pankow                      Der neue Preis beträgt 169 €
169 €                                              NaN                                                  NaN
Mondrian Suites Berlin Checkpoint Charlie          Berlin                      Der neue Preis beträgt 221 €
221 €                                              NaN                                                  NaN
Angleterre Hotel                                   Berlin                      Der neue Preis beträgt 227 €
227 €                                              NaN                                                  NaN
Hotel MANI by AMANO Group                          Mitte                            Der Preis beträgt 209 €
209 €                                              NaN                                                  NaN
Bett & Buch Hotel                                  Berlin                       Der neue Preis beträgt 81 €
81 €                                               NaN                                                  NaN
Holiday Inn Berlin - City East Side                Berlin                           Der Preis beträgt 173 €
173 €                                              NaN                                                  NaN
Sheraton Berlin Grand Hotel Esplanade              Mitte                            Der Preis beträgt 513 €
513 €                                              NaN                                                  NaN
Hotel Pankow                                       Pankow                           Der Preis beträgt 103 €
103 €                                              NaN                                                  NaN
Hotel PLUS Berlin                                  Berlin                           Der Preis beträgt 137 €
137 €                                              NaN                                                  NaN
IBB Blue Hotel Adlershof Berlin-Airport            Berlin                            Der Preis beträgt 98 €
98 €                                               NaN                                                  NaN
Victor's Residenz-Hotel Berlin                     Pankow                           Der Preis beträgt 228 €
228 €                                              NaN                                                  NaN
Adele Designhotel                                  Pankow                      Der neue Preis beträgt 144 €
144 €                                              NaN                                                  NaN
Orania.Berlin                                      Berlin                           Der Preis beträgt 414 €
414 €                                              NaN                                                  NaN
Grimms Hotel Berlin Mitte                          Mitte                            Der Preis beträgt 193 €
193 €                                              NaN                                                  NaN
Gorki Apartments Berlin                            Mitte                       Der neue Preis beträgt 478 €
478 €                                              NaN                                                  NaN
Hotel Riu Plaza Berlin                             Berlin                           Der Preis beträgt 278 €
278 €                                              NaN                                                  NaN
Schlosshotel Berlin by Patrick Hellmann            Charlottenburg-Wilmersdorf       Der Preis beträgt 428 €
428 €                                              NaN                                                  NaN
Hotel Zarenhof Friedrichshain                      Berlin                      Der neue Preis beträgt 160 €
160 €                                              NaN                                                  NaN
INNSiDE by Melia Berlin Mitte                      Mitte                            Der Preis beträgt 192 €
192 €                                              NaN                                                  NaN
Die Botschaft                                      Lichtenberg                       Der Preis beträgt 58 €
58 €                                               NaN                                                  NaN
Regent Berlin                                      Mitte                            Der Preis beträgt 480 €
480 €                                              NaN                                                  NaN
Adina Apartment Hotel Berlin CheckPoint Charlie    Mitte                       Der neue Preis beträgt 229 €
229 €                                              NaN                                                  NaN
Hotel Buchholz                                     Pankow                           Der Preis beträgt 116 €
116 €                                              NaN                                                  NaN
AZIMUT Hotel City South Berlin                     Neukölln                    Der neue Preis beträgt 117 €
117 €                                              NaN                                                  NaN
a&o Berlin Hauptbahnhof                            Mitte                            Der Preis beträgt 112 €
112 €                                              NaN                                                  NaN
Hotel & Apartments Zarenhof Berlin Prenzlauer Berg Pankow                      Der neue Preis beträgt 179 €
179 €                                              NaN                                                  NaN
acama Hotel & Hostel Kreuzberg                     Berlin                            Der Preis beträgt 98 €
98 €                                               NaN                                                  NaN
Bed'n'Work Apartment Friedrichshain                Berlin                           Der Preis beträgt 119 €
119 €                                              NaN                                                  NaN
The Aga's Hotel Berlin                             Berlin                       Der neue Preis beträgt 51 €
51 €                                               NaN                                                  NaN
a&o Berlin Friedrichshain                          Berlin                       Der neue Preis beträgt 49 €
49 €                                               NaN                                                  NaN
Boutique Hotel Fährhaus                            Spandau                          Der Preis beträgt 150 €
150 €                                              NaN                                                  NaN
CHECK IN HOTEL                                     Berlin                            Der Preis beträgt 89 €
89 €                                               NaN                                                  NaN
The Belfort Berlin                                 Pankow                           Der Preis beträgt 251 €
251 €                                              NaN                                                  NaN
Lux 11 Berlin Mitte                                Mitte                       Der neue Preis beträgt 393 €
393 €                                              NaN                                                  NaN
Ocak Apartment & Hotel Berlin                      Mitte                       Der neue Preis beträgt 179 €
179 €                                              NaN                                                  NaN
Luxoise Apartments Berlin Friedrichshain           Berlin                           Der Preis beträgt 126 €
126 €                                              NaN                                                  NaN
Holiday Inn Berlin City Center East Prenzlauer ... Pankow                           Der Preis beträgt 193 €
193 €                                              NaN                                                  NaN
Michelberger Hotel Berlin                          Berlin                           Der Preis beträgt 226 €
226 €                                              NaN                                                  NaN
MEININGER Hotel Berlin Tiergarten                  Mitte                            Der Preis beträgt 205 €
205 €                                              NaN                                                  NaN
Holiday-Apartments Frankfurter Allee 98            Berlin                           Der Preis beträgt 184 €
184 €                                              NaN                                                  NaN
Max Brown Kudamm                                   Charlottenburg-Wilmersdorf       Der Preis beträgt 278 €
278 €                                              NaN                                                  NaN
NH Collection Berlin Mitte am Checkpoint Charlie   Mitte                            Der Preis beträgt 375 €
375 €                                              NaN                                                  NaN
Henri Hotel - Berlin Kurfürstendamm                Charlottenburg-Wilmersdorf       Der Preis beträgt 315 €
315 €                                              NaN                                                  NaN
Come Inn Berlin Kurfürstendamm                     Charlottenburg-Wilmersdorf  Der neue Preis beträgt 318 €
318 €                                              NaN                                                  NaN
OYO Hotel Bohemia                                  Neukölln                         Der Preis beträgt 119 €
119 €                                              NaN                                                  NaN
Pension Prenzlberg                                 Pankow                           Der Preis beträgt 145 €
145 €                                              NaN                                                  NaN
Safestay Berlin                                    Berlin                           Der Preis beträgt 208 €
208 €                                              NaN                                                  NaN
City Guesthouse Pension Berlin                     Pankow                           Der Preis beträgt 125 €
125 €                                              NaN                                                  NaN
Mercure Hotel Berlin am Alexanderplatz             Mitte                            Der Preis beträgt 186 €
186 €                                              NaN                                                  NaN
Hapimag Resort Berlin Zoo                          Mitte                            Der Preis beträgt 258 €
258 €                                              NaN                                                  NaN
Hollywood Media Hotel                              Charlottenburg-Wilmersdorf       Der Preis beträgt 262 €
262 €                                              NaN                                                  NaN
Hotel Metropolitan Berlin                          Charlottenburg-Wilmersdorf       Der Preis beträgt 116 €
116 €                                              NaN                                                  NaN
Pension Thomas                                     Berlin                       Der neue Preis beträgt 52 €
52 €                                               NaN                                                  NaN
NH Berlin Alexanderplatz                           Berlin                           Der Preis beträgt 383 €
383 €                                              NaN                                                  NaN
Enjoy Hotel Berlin City Messe                      Charlottenburg-Wilmersdorf       Der Preis beträgt 226 €
226 €                                              NaN                                                  NaN
NH Berlin Kurfürstendamm                           Charlottenburg-Wilmersdorf       Der Preis beträgt 396 €
396 €                                              NaN                                                  NaN
Berlin Marriott Hotel                              Mitte                            Der Preis beträgt 508 €
508 €                                              NaN                                                  NaN
Teikyo Hotel                                       Berlin                            Der Preis beträgt 59 €
59 €                                               NaN                                                  NaN
Excellent-Apartments Kreuzberg                     Berlin                            Der Preis beträgt 95 €
95 €                                               NaN                                                  NaN
arabel Design Apartments Berlin                    Mitte                       Der neue Preis beträgt 277 €
277 €                                              NaN                                                  NaN
Amc Apartments Ku Damm                             Charlottenburg-Wilmersdorf       Der Preis beträgt 293 €
293 €                                              NaN                                                  NaN
Wilde Aparthotels by Staycity Berlin Checkpoint... Mitte                            Der Preis beträgt 226 €
226 €                                              NaN                                                  NaN
Aparthotel-Christie                                Berlin                           Der Preis beträgt 311 €
311 €                                              NaN                                                  NaN
Super Berlin Ferienwohnung                         Pankow                           Der Preis beträgt 275 €
275 €                                              NaN                                                  NaN
Design Hostel P182                                 Berlin                            Der Preis beträgt 55 €
55 €                                               NaN                                                  NaN
Teikyo Berlin Jugendgästehaus                      Berlin                            Der Preis beträgt 41 €
41 €                                               NaN                                                  NaN
Insor                                              Berlin                            Der Preis beträgt 80 €
80 €                                               NaN                                                  NaN
Mikon Eastgate Hotel                               Mitte                            Der Preis beträgt 341 €
341 €                                              NaN                                                  NaN
Hotel De Ela                                       Berlin                           Der Preis beträgt 106 €
106 €                                              NaN                                                  NaN
City landmark near Checkpoint Charlie              Berlin                      Der neue Preis beträgt 434 €
434 €                                              NaN                                                  NaN
Hotel Pension Rheingold                            Charlottenburg-Wilmersdorf       Der Preis beträgt 198 €
198 €                                              NaN                                                  NaN
M I N I T E L                                      Neukölln                         Der Preis beträgt 351 €
351 €                                              NaN                                                  NaN
All In Hostel / Hotel Berlin                       Berlin                       Der neue Preis beträgt 26 €
26 €                                               NaN                                                  NaN
The Circus Hostel                                  Mitte                        Der neue Preis beträgt 46 €
46 €                                               NaN                                                  NaN
Ostel - Das DDR Design Hostel Berlin               Berlin                            Der Preis beträgt 51 €
51 €                                               NaN                                                  NaN
Haus am Wald mit Garten in Tegel Ruhige Lage Se... Berlin                           Der Preis beträgt 660 €
660 €                                              NaN                                                  NaN
Grand Hostel Berlin Classic                        Berlin                            Der Preis beträgt 67 €
67 €                                               NaN                                                  NaN
one80º Hostel Berlin                               Mitte                        Der neue Preis beträgt 34 €
34 €                                               NaN                                                  NaN

In [8]:
data = data.iloc[1::2]

In [9]:
data = data.reset_index()
data = data.drop(["index"],axis=1)
data

   level_0  level_1 112 €
0    245 €      NaN   NaN
1    186 €      NaN   NaN
2    108 €      NaN   NaN
3    221 €      NaN   NaN
4    173 €      NaN   NaN
5     98 €      NaN   NaN
6    193 €      NaN   NaN
7    160 €      NaN   NaN
8    229 €      NaN   NaN
9    179 €      NaN   NaN
10    49 €      NaN   NaN
11   393 €      NaN   NaN
12   226 €      NaN   NaN
13   375 €      NaN   NaN
14   145 €      NaN   NaN
15   258 €      NaN   NaN
16   383 €      NaN   NaN
17    59 €      NaN   NaN
18   226 €      NaN   NaN
19    41 €      NaN   NaN
20   434 €      NaN   NaN
21    46 €      NaN   NaN
22    34 €      NaN   NaN
23    85 €      NaN   NaN

In [10]:
data = data.drop(["Der Preis beträgt 468 €"],axis=1)

KeyError: "['Der Preis beträgt 468 €'] not found in axis"

In [ ]:
data

In [ ]:
data = data.rename(columns={"The Ritz-Carlton": "hotel_name", " Berlin":"area", "Mitte":"price"})

In [ ]:
data = data.append(pd.Series(["The Ritz-Carlton", "Mitte", "468 €"], index=data.columns ), ignore_index=True)

In [ ]:
data=data.sort_values(by=['hotel_name'])